---
title: "S&DS425_CaseStudy4"
output: html_document
date: "2025-11-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(arrow)
library(dplyr)
```

```{r}
file1 <- read_parquet('train-00000-of-00007.parquet')
file2 <- read_parquet('train-00001-of-00007.parquet')
file3 <- read_parquet('train-00002-of-00007.parquet')
file4 <- read_parquet('train-00003-of-00007.parquet')
file5 <- read_parquet('train-00004-of-00007.parquet')
file6 <- read_parquet('train-00005-of-00007.parquet')
file7 <- read_parquet('train-00006-of-00007.parquet')
```

```{r}
clean <- function(dataframe){
  dataframe <- dataframe %>% 
  select(-c('full_conversation', 'conversation_a', 'conversation_b'))
}
```

```{r}
file1_cl <- clean(file1)
file2_cl <- clean(file2)
file3_cl <- clean(file3)
file4_cl <- clean(file4)
file5_cl <- clean(file5)
file6_cl <- clean(file6)
file7_cl <- clean(file7)
```
```{r}
library(tidyr)
library(purrr)
```

```{r}
unnest <- function(dataframe){
  while
  dataframe = dataframe %>% unnest_wider(c('conv_metadata', 'category_tag'))
  for(i in 1:ncol(dataframe)){
    if 
  }
}
```

```{r}
file1_unnest <- unnest(file1_cl)
```

```{r}
final_data <- read.csv('combined_clean_flat.csv')
```

```{r}
final_data_awin = final_data %>% filter(winner == 'model_a')
final_data_bwin = final_data %>% filter(winner == 'model_b')
final_data_tie = final_data %>% filter(winner == 'tie')
final_data_bothbad = final_data %>% filter(winner == 'both_bad')
```
```{r}
sort(table(final_data_awin$model_a))
```

```{r}
results <- list()

for (model in unique(final_data_awin$model_a)) {
  temp <- final_data_awin %>%
    filter(model_a == model) %>%
    count(model_b) %>%
    pivot_wider(
      names_from = model_b,
      values_from = n,
      values_fill = 0
    ) %>%
    mutate(model = model) # add column directly
  
  results[[model]] <- temp
}

loss_data <- bind_rows(results)

#do the same for model_b wins
results_b <- list()

for (model in unique(final_data_bwin$model_b)) {
  temp <- final_data_bwin %>%
    filter(model_b == model) %>%
    count(model_a) %>%
    pivot_wider(
      names_from = model_a,
      values_from = n,
      values_fill = 0
    ) %>%
    mutate(model = model) # add column directly
  
  results_b[[model]] <- temp
}

loss_data_b <- bind_rows(results_b)
```

```{r}
loss_data <- loss_data %>%
  relocate(model, .before = everything())
loss_data_b <- loss_data_b %>%
  relocate(model, .before = everything())
```
```{r}
loss_data <- loss_data %>%
  select(model, all_of(loss_data$model))
#reorder loss_data_b in the same way as loss_data is ordered
loss_data_b <- loss_data_b %>%
  select(model, all_of(loss_data$model))
#reorder rows of loss_data_b to match loss_data
loss_data_b <- loss_data_b %>%
  slice(match(loss_data$model, loss_data_b$model))
```

```{r}
#make the first column just rownames and then make the full dataframe numeric
models <- loss_data$model
loss_data <- loss_data %>%
  select(-model)
loss_data <- as.data.frame(sapply(loss_data, as.numeric))

loss_data_b <- loss_data_b %>%
  select(-model)
loss_data_b <- as.data.frame(sapply(loss_data_b, as.numeric))

loss_data = loss_data + loss_data_b
```

```{r}
n <- nrow(loss_data)
win_pct <- matrix(NA, n, n, dimnames = list(rownames(loss_data), colnames(loss_data)))
#set diagonals to 0
# Compute pairwise win percentages
for (i in 1:n) {
  for (j in 1:n) {
    if (i != j & !is.na(loss_data[i, j]) & !is.na(loss_data[j, i])) {
      total_matches <- loss_data[i, j] + loss_data[j, i]
      if (total_matches > 0) {
        win_pct[i, j] <- loss_data[i, j] / total_matches
      } else {
        win_pct[i, j] <- NA  # no games between i and j
      }
    }
  }
}
```
```{r}
win_pct_df <- as.data.frame(win_pct)
win_pct_df <- cbind(models, win_pct_df)
```





